SPDX-FileCopyrightText: 2023 Holger Kienle
SPDX-License-Identifier: CC0-1.0

FPGA
* TODO learning resources
** TODO lessons and labs https://github.com/litex-hub/fpga_101
** FPGA Tomu Workshop  https://workshop.fomu.im/en/latest/
** IceStorm Learner’s Documentation (2017) https://hedmen.org/icestorm-doc/icestorm.html
  - outdated?
  - does not cover UP chips, but perhaps very similar
** Jordan Christman – Getting Started With FPGAs https://techexplorations.com/guides/summits/maker-mind-meld/jordan-christman-getting-started-with-fpgas/
12:35 development process (IP catalog, state machine, simulation for debugging, synthesis, ...)
16:37 FPGA vs. uC (power management)
20:19 Xilink (now AMD) / Intel (Altera)
22:40 dev boards (Digilent BASYS 3 good as a start), Pmod extension boards, Arty series (fits Arduino shields)
26:40 project demo with Arty A7: buttons, LEDs, EN-switch
  35:33 generate design
42:25 Q: IP catalog (e.g., RS232)
* landscape
https://towardsdatascience.com/introduction-to-fpga-and-its-architecture-20a62c14421c
- FPGA chips
  - all proprietary
  - major players: Xilinx (AMD) and Intel (formerly Altera)
  - minor players
    - Lattice
      - "After AMD completed the acquisition of Xilinx in February
        2022, Lattice Semiconductor became the last fully independent
        major manufacturer of FPGAs."  https://en.wikipedia.org/wiki/Lattice_Semiconductor#Operations
      - open source friendly/tolerating  https://hackaday.com/2020/06/06/lattice-drops-eula-clause-forbidding-fpga-bitstream-reverse-engineering/
      - !! GOWIN (China)  https://www.gowinsemi.com/en/
- architecture
  https://towardsdatascience.com/introduction-to-fpga-and-its-architecture-20a62c14421c
  - logic blocks :: "implement the logical functions required by the
    design and consist of various components such as transistor pairs,
    *look-up tables* (LUTs), flip flops, and multiplexers"
  - programmable interconnect :: "hook [logic blocks] together by
    programming the interconnects"
- memory types  https://projectf.io/posts/fpga-memory-types/
  - flips-flops :: 1-bit state/register (number of flip-flop is always the same as number of LUTs?)
  - DRAM :: distributed RAM is built with LUTs (not supported by all FPGAs)
    - high latency for random access (sequential works well)
    - "complex to interface with: you’re almost certainly going to
      have to use vendor IP blocks and a cache to make DRAM usable"
  - BRAM :: block RAM
  - SRAM :: static RAM, high speed but costly (not supported by all FPGAs, but iCE40 UP has it)
- IP blocks
  - FOSS collection of IP blocks  https://opencores.org/
  - soft macro/block :: "A soft macro is the RTL [sic: HDL?] (VHDL or
    Verilog) that describes the functional implementation of the
    IP. This is compiled into a gate-level netlist, which is then
    turned into a physical layout to produce the mask set for
    manufacturing."  https://electronics.stackexchange.com/a/226841/305687
  - hard macro/block ::  "A hard macro is a physical layout of the IP
    suitable for a given process. It's added to the larger chip layout
    as a single block, which saves some steps in the design process."
- bitstream format
  - not disclosed by manufacturer
    - allows closed/expensive IP blocks (?)
    - manufacturer can charge for its tools
    - reverse engineering with fuzzing
  - "The details of a specific FPGA's bitstream format (which defines
    how the internal elements of the FPGA are connected and interact
    with each other) are not usually published by FPGA vendors. This
    means that, generally, an engineer creating a design for an FPGA
    must use the tools provided by the FPGA's manufacturer."  [[https://en.wikipedia.org/wiki/ICE_(FPGA)#Development]]
  - many reverse engineering efforts
    - Lattice ECP5  https://prjtrellis.readthedocs.io/en/latest/index.html
    - Lattice iCE
    - Anlogic  https://github.com/mmicko/prjtang
  - bitstream compression/compaction is desirable  https://github.com/nmi-leipzig/compact_bitstream
* chips
** Lattice iCE40 UltraPlus (iCE40-UP5K and iCE40-UP3K)  [[https://en.wikipedia.org/wiki/ICE_(FPGA)#iCE40_Ultra,_UltraLite,_&_UltraPlus]]
- ...40 derives from 40 nm process
- on the market since 2016 (HX is older)
- best FOSS support (?)
  - IceStorm has "support for iCE40 UltraPlus devices"  http://bygone.clairexen.net/icestorm/
  - Yosys tooling for iCE40 "enables a level of transparency and
    reproducibility that make iCE40 FPGAs highly suited for scientific
    research"  https://www.easychair.org/publications/preprint/TPpq
*** doc
file:~/prj/ee-parts/ic-ice40up.pdf
datasheet https://www.latticesemi.com/en/Products/FPGAandCPLD/iCE40UltraPlus#_1583858FEF1D4406B570F0CACD485268
https://hedmen.org/icestorm-doc/icestorm.html#Lattice-iCE40-1K-and-8K-FPGAs
YT: Architecture and Technical Details (Part 2)  https://www.youtube.com/watch?v=UlgJ7TRU1KI
*** buy
EUR 8,89  https://www.mouser.de/ProductDetail/Lattice/ICE40UP5K-SG48I
EUR 8,36  https://www.digikey.de/en/products/detail/lattice-semiconductor-corporation/ICE40UP5K-SG48I/7785190
*** architecture
- LC :: logical cell
  - 1 LUT and 1 D-style flip-flop (DFF)
- LUT :: look up tables (combinational logic, specifies "truth table")  https://electronics.stackexchange.com/questions/169532/what-is-an-lut-in-fpga
  - ...-5K has 5280 LUT
  - ...-3K has 2800 LUT
  - up to 4 inputs -> " behaves as a 16x1 Read-Only Memory "
- PLB :: programmable logic block
  - consists of 8 interconnected LCs
- NVCM for one-time(!) customization
- SPI for programming (dedicated pins, can bypass NVCM)
- hard blocks: I2C, SPI, DSP, RGB LED drivers, I3C, etc.
- I/O banks, each configurable for a different voltage (1.8-3.3V) -> I/O pins
- PLL -> I/O pins
- SRAM 4x256kb
  - single port
  - can be cascaded to 1x1Mb  https://projectf.io/posts/spram-ice40-fpga/
- delay lines
- 24mA constant current sink (RGB LED or open drain)
** GOWIN GW1N series
FOSS support (maturity?) https://github.com/YosysHQ/apicula
* boards
** PMOD extension boards  https://pmod.org/#/about
- open standard (according to Digilent)
- can use either SPI, I2C or UART protocol
- broad range of functionality
  - 8 LEDs (iceSugar)
  - 8 switches (1bitsquared, iceSugar)
  - 2x7-segment display (1bitsquared)
  - DAC and ADC (Olimex)
  - VGA (iceSugar, Olimex)
  - HDMI (1bitsquared)
  - audio (iceSugar)
*** buy
https://1bitsquared.de/search?type=product&q=pmod
https://github.com/icebreaker-fpga/icebreaker-pmod
** !! ICEbreaker - iCE40 UltraPlus 5K  https://github.com/icebreaker-fpga/icebreaker
cf. file:./board-icebreaker.org
** !! iCESugar (Muse Lab)  v1.5 - iCE40 UltraPlus 5K
ICEBreaker clone/iteration?
https://github.com/wuxx/icesugar/blob/master/README_en.md
store https://miusecntech-muselab.aliexpress.com/store/5940159
** Fomu - iCE40 UltraPlus 5K
https://github.com/im-tomu/fomu-hardware
https://www.crowdsupply.com/sutajio-kosagi/fomu
** Olimex - iCE40  https://www.olimex.com/Products/FPGA/iCE40/
*** iCE40HX1K-EVB
https://github.com/OLIMEX/iCE40HX1K-EVB
buy (EUR 15,95)  https://www.olimex.com/Products/FPGA/iCE40/iCE40HX1K-EVB/open-source-hardware
*** iCE40HX8K-EVB
buy (EUR 25,95)  https://www.olimex.com/Products/FPGA/iCE40/iCE40HX8K-EVB/open-source-hardware
** OrangeCrab - Lattice ECP5-25F https://orangecrab-fpga.github.io/orangecrab-hardware/r0.2/
** UPduino v3.1 - iCE40 UltraPlus 5K https://github.com/tinyvision-ai-inc/UPduino-v3.0
buy https://lectronz.com/products/upduino-v3-1-low-cost-lattice-ice40-fpga-board
examples with icestorm https://github.com/osresearch/up5k
** ULX3S - Lattice ECP5 https://radiona.org/ulx3s/
- "you can also use the ULX3S as powerful Arduino and program it using
  Arduino IDE in seconds"
** Alhambra II - iCE40HX4K  https://alhambrabits.com/alhambra/
** BlackIce Mx - iCE40 HX4K  https://github.com/folknology/IceCore
** Tang Nano 9K (GOWIN GW1NR-9)
GW1NR-9 chip: GW1N (Traditional FPGA) + integrated RAM  https://www.gowinsemi.com/en/product/detail/46/
https://wiki.sipeed.com/hardware/en/tang/Tang-Nano-9K/Nano-9K.html
https://github.com/sipeed/TangNano-9K-example/tree/main/picotiny
PicoRV32 RISC-V soft-core with all peripherals  https://www.cnx-software.com/2022/01/17/tang-nano-9k-fpga-board-can-emulate-picorv32-risc-v-soft-core-with-all-peripherals/
* software
** TODO OSS CAD Suite  https://github.com/YosysHQ/oss-cad-suite-build
apio-packaged subset of tools  https://github.com/FPGAwars/tools-oss-cad-suite
obsolete https://github.com/YosysHQ/fpga-toolchain
** TODO LiteX  https://github.com/enjoy-digital/litex
- slides https://docs.google.com/presentation/d/1mQOWqgmyQxpjLAzFwCulqgkp0TuxmaIDYp5iUfPqqIk/edit#slide=id.p
- HDL: Migen  https://github.com/m-labs/migen
  - "integrate VHDL/Verilog/SystemVerilog/nMigen/Spinal-HDL code in LiteX"
  - "generate the LiteX design as a verilog file and integrate it in a traditional flow"
- supported boards  https://github.com/litex-hub/litex-boards#-boards-list
  - icebreaker, muselab_icesugar, lattice_ice40up5k_evn
- "supports various softcores CPUs: VexRiscv, Rocket, LM32, Mor1kx, PicoRV32, BlackParrot"
** F4PGA Open source FPGA toolchain  https://f4pga.org/
https://github.com/f4pga
- initated by CHIPS Alliance in Feb 2022  https://chipsalliance.org/announcement/2022/02/18/chips-alliance-forms-f4pga-workgroup-to-accelerate-adoption-of-open-source-fpga-tooling/
  - "focused around the free and open source FPGA toolchain formerly
    known as SymbiFlow"
  - FPGA Interchange format to enable interoperable FPGA tooling  https://opensource.googleblog.com/2022/02/FPGA%20Interchange%20format%20to%20enable%20interoperable%20FPGA%20tooling.html
  - it seems suspect that companies like Intel and Xilinx are
    involved, which do NOT publist their bitstream format
** nextpnr -- a portable FPGA place and route tool  https://github.com/YosysHQ/nextpnr
- Arachne-pnr is obsolete  https://github.com/YosysHQ/arachne-pnr
- vendor neutral, there are dedicated board/chip projects
** icestorm  https://github.com/YosysHQ/icestorm
- no releases (grab latest)  https://github.com/YosysHQ/icestorm/issues/217
https://hedmen.org/icestorm-doc/icestorm.html
** ?? OpenROAD https://github.com/The-OpenROAD-Project/OpenROAD
** openFPGALoader
- supported boards  https://trabucayre.github.io/openFPGALoader/compatibility/board.html
  - ice40_generic covers iCEBreaker  https://hdl.github.io/constraints/Data/Boards/index.html#boards-icebreaker
    - memory support not available (?)
** iceprog  https://github.com/YosysHQ/icestorm/tree/master/iceprog
iceprog leaves FTDI device in odd mode  https://github.com/YosysHQ/icestorm/issues/194
** bitstream compaction (research tool)
https://github.com/nmi-leipzig/compact_bitstream
https://www.easychair.org/publications/preprint/TPpq
** Lattice Diamond
- .jed is the default format generated by Lattice Diamond
- free version with yearly renewal  https://www.latticesemi.com/latticediamond#_FD13D8A25CBB47BD83F143E5B55DBC75
** Xilinx Vivado ML Standard is free and runs on Linux  https://www.xilinx.com/products/design-tools/vivado/vivado-ml.html#licensing
impression (2017): Vivado does no care about space efficiency  https://www.bunniestudios.com/blog/?p=5018
* CPU soft cores
- FOSS candidates: RISC-V and Propeller 1
- patent protection
  - it seems an ISA can be cloned/re-implemented if there is no patent protection
  - !? only individual instructions can be covered by a patent, not the ISA as a whole  https://news.ycombinator.com/item?id=15404084
  - example: "The older v2a version of the *ARM instruction set* is
    supported because it [...] is not covered by patents so can be
    implemented without a license from ARM"  https://opencores.org/projects/amber
* Arduino-related approaches
discussion  https://github.com/icebreaker-fpga/icebreaker/issues/39
tweak Arduino IDE to use as bitstream uploader  https://github.com/drtrigon/fpgarduino-icestorm
